export const queryKeys = {
  blocks: () => ['blocks'] as const,
  blocksByDateRoot: () => ['blocks', 'by-date'] as const,
  blocksFlat: () => ['blocks-flat'] as const,
  blocksByDate: (date: string) => ['blocks', 'by-date', date] as const,
  blockCleanupDays: () => ['blocks', 'cleanup-days'] as const,
  tags: () => ['tags'] as const,
  notebooks: () => ['notebooks'] as const,
  notebookRoot: () => ['notebook'] as const,
  notebook: (notebookId: string) => ['notebook', notebookId] as const,
  graphRoot: () => ['graph'] as const,
  graph: (activeTagFilters: string[]) => ['graph', activeTagFilters] as const,
  snapshotsRoot: () => ['snapshots'] as const,
  snapshots: (snapshotQuery: string, notebookIdOrNull: string | null = null) => ['snapshots', snapshotQuery, notebookIdOrNull] as const,
  calendarRoot: () => ['calendar'] as const,
  calendarYears: () => ['calendar', 'years'] as const,
  calendarDayRoot: () => ['calendar', 'day'] as const,
  calendarHeatmap: (year: number) => ['calendar', 'heatmap', year] as const,
  calendarDay: (date: string) => ['calendar', 'day', date] as const,
  calendarUpcoming: (limitDays: number) => ['calendar', 'upcoming', limitDays] as const,
  reviewRoot: () => ['review'] as const,
  reviewDailyRoot: () => ['review', 'daily'] as const,
  reviewInsightRoot: () => ['review', 'insight'] as const,
  reviewDaily: (language: string, date: string, requestVersion = 0) => ['review', 'daily', language, date, requestVersion] as const,
  reviewInsight: (language: string, methodId: string, date: string, requestVersion = 0) => ['review', 'insight', language, methodId, date, requestVersion] as const,
  reviewInsightHistoryRoot: () => ['review', 'insight-history'] as const,
  reviewInsightHistory: (language: string, methodId: string | null = null, limit = 30) => ['review', 'insight-history', language, methodId ?? 'all', limit] as const,
  settingsRoot: () => ['settings'] as const,
  setting: (key: string) => ['settings', key] as const,
  dataManagement: () => ['data-management'] as const,
  meta: () => ['meta'] as const,
}
