export const queryKeys = {
  blocks: () => ['blocks'] as const,
  blocksByDate: (date: string) => ['blocks', 'by-date', date] as const,
  blockCleanupDays: () => ['blocks', 'cleanup-days'] as const,
  tags: () => ['tags'] as const,
  notebooks: () => ['notebooks'] as const,
  notebookRoot: () => ['notebook'] as const,
  notebook: (notebookId: string) => ['notebook', notebookId] as const,
  graphRoot: () => ['graph'] as const,
  graph: (activeTagFilters: string[]) => ['graph', activeTagFilters] as const,
  snapshotsRoot: () => ['snapshots'] as const,
  snapshots: (snapshotQuery: string, notebookIdOrNull: string | null = null) => ['snapshots', snapshotQuery, notebookIdOrNull] as const,
  calendarRoot: () => ['calendar'] as const,
  calendarYears: () => ['calendar', 'years'] as const,
  calendarHeatmap: (year: number) => ['calendar', 'heatmap', year] as const,
  calendarDay: (date: string) => ['calendar', 'day', date] as const,
  calendarUpcoming: (limitDays: number) => ['calendar', 'upcoming', limitDays] as const,
  dataManagement: () => ['data-management'] as const,
  meta: () => ['meta'] as const,
}
