export const IPC_CHANNELS = {
  blocks: {
    create: 'blocks:create',
    get: 'blocks:get',
    getMany: 'blocks:get-many',
    getContext: 'blocks:get-context',
    list: 'blocks:list',
    listByDate: 'blocks:list-by-date',
    update: 'blocks:update',
    remove: 'blocks:remove',
    removeMany: 'blocks:remove-many',
    findRelated: 'blocks:find-related',
  },
  search: {
    blocks: 'search:blocks',
    byTag: 'search:by-tag',
    generate: 'search:generate',
  },
  attachments: {
    saveImage: 'attachments:save-image',
  },
  graph: {
    getData: 'graph:get-data',
  },
  tags: {
    add: 'tags:add',
    remove: 'tags:remove',
    list: 'tags:list',
  },
  snapshots: {
    save: 'snapshots:save',
    list: 'snapshots:list',
    get: 'snapshots:get',
    remove: 'snapshots:remove',
  },
  calendar: {
    listYears: 'calendar:list-years',
    getYearHeatmap: 'calendar:get-year-heatmap',
    getDayDetail: 'calendar:get-day-detail',
    listUpcoming: 'calendar:list-upcoming',
    createEntry: 'calendar:create-entry',
    updateEntry: 'calendar:update-entry',
    removeEntry: 'calendar:remove-entry',
    acceptSuggestion: 'calendar:accept-suggestion',
    dismissSuggestion: 'calendar:dismiss-suggestion',
  },
  notebooks: {
    list: 'notebooks:list',
    get: 'notebooks:get',
    create: 'notebooks:create',
    update: 'notebooks:update',
    remove: 'notebooks:remove',
    addBlock: 'notebooks:add-block',
    removeItem: 'notebooks:remove-item',
    reorderItems: 'notebooks:reorder-items',
    createBlock: 'notebooks:create-block',
    createStructureItem: 'notebooks:create-structure-item',
    updateStructureItem: 'notebooks:update-structure-item',
    getReferencePreview: 'notebooks:get-reference-preview',
    updateReferenceReview: 'notebooks:update-reference-review',
    generateDocument: 'notebooks:generate-document',
  },
  exports: {
    markdown: 'exports:markdown',
    json: 'exports:json',
  },
  imports: {
    previewMarkdown: 'imports:preview-markdown',
    previewJson: 'imports:preview-json',
    confirm: 'imports:confirm',
  },
  data: {
    getOverview: 'data:get-overview',
    cleanupOrphanAttachments: 'data:cleanup-orphan-attachments',
    rebuildAttachmentIndex: 'data:rebuild-attachment-index',
    rebuildAllVectors: 'data:rebuild-all-vectors',
  },
  review: {
    openWindow: 'review:open-window',
    generateDaily: 'review:generate-daily',
    generateInsight: 'review:generate-insight',
    listInsightHistory: 'review:list-insight-history',
    startDailyGeneration: 'review:start-daily-generation',
    startInsightGeneration: 'review:start-insight-generation',
    saveDailySnapshot: 'review:save-daily-snapshot',
    saveInsightSnapshot: 'review:save-insight-snapshot',
  },
  settings: {
    get: 'settings:get',
    set: 'settings:set',
    testApi: 'settings:test-api',
    openWindow: 'settings:open-window',
    openDataDirectory: 'settings:open-data-directory',
    openSettingsDirectory: 'settings:open-settings-directory',
    getMeta: 'settings:get-meta',
    getExternalAccessStatus: 'settings:get-external-access-status',
    enableExternalAccess: 'settings:enable-external-access',
    generateExternalAccessBundle: 'settings:generate-external-access-bundle',
    setupExternalAccess: 'settings:setup-external-access',
    disableExternalAccess: 'settings:disable-external-access',
    openExternalAccessDirectory: 'settings:open-external-access-directory',
  },
  vectors: {
    retryFailed: 'vectors:retry-failed',
  },
  events: {
    batch: 'events:batch',
    blockChanged: 'events:block-changed',
    notebooksChanged: 'events:notebooks-changed',
    metaChanged: 'events:meta-changed',
    calendarChanged: 'events:calendar-changed',
    docGenerationChunk: 'events:doc-generation-chunk',
    reviewGenerationChunk: 'events:review-generation-chunk',
    quitStateChanged: 'events:quit-state-changed',
  },
} as const
