export interface DefaultTagDefinition {
  category: string
  name: string
  keywords: string[]
}

export const CATEGORY_TAG_NAMES = ['技术', '学习', '工作', '生活', '创意', '内容']

export const DEFAULT_TAG_DEFINITIONS: DefaultTagDefinition[] = [
  { category: '技术', name: '编程', keywords: ['编程', '代码', '开发', '函数', '脚本', '程序', 'typescript', 'javascript'] },
  { category: '技术', name: '前端', keywords: ['前端', '页面', '组件', '浏览器', 'react', 'vite', 'tailwind', 'ui'] },
  { category: '技术', name: '后端', keywords: ['后端', '服务端', '接口', 'api', 'server', '路由', '鉴权', '中间件'] },
  { category: '技术', name: '数据库', keywords: ['数据库', 'sqlite', 'sql', '表', '索引', '查询', '迁移', 'schema', '向量库'] },
  { category: '技术', name: 'AI', keywords: ['ai', 'llm', '模型', 'prompt', 'embedding', '智能', '推理', 'gpt', '向量', 'vector', 'siliconflow', 'minimax', 'bge'] },
  { category: '技术', name: '运维', keywords: ['运维', '部署', '容器', 'docker', '日志', '监控', 'ci', 'cd'] },
  { category: '技术', name: '网络', keywords: ['网络', 'http', 'https', 'tcp', 'dns', '请求', '带宽', '代理'] },
  { category: '技术', name: '工具', keywords: ['工具', '软件', '命令', '终端', '插件', '自动化', '效率', 'workflow'] },
  { category: '学习', name: '读书笔记', keywords: ['读书', '书摘', '书单', '章节', '作者', '笔记'] },
  { category: '学习', name: '课程', keywords: ['课程', '课件', '作业', '讲义', '训练营', '学习班'] },
  { category: '学习', name: '论文', keywords: ['论文', 'paper', '摘要', '实验', '研究方法', '引用'] },
  { category: '学习', name: '概念', keywords: ['概念', '定义', '原理', '术语', '理解', '知识点'] },
  { category: '学习', name: '教程', keywords: ['教程', '指南', '步骤', '入门', '示例', '怎么做'] },
  { category: '工作', name: '任务', keywords: ['任务', 'todo', '待办', '完成', '截止', '跟进', '修复', '处理', '实现'] },
  { category: '工作', name: '会议', keywords: ['会议', '纪要', '对齐', '同步', '讨论', '会后'] },
  { category: '工作', name: '项目', keywords: ['项目', '版本', 'mvp', '里程碑', '交付', '需求', '测试', '验证', '接入', '联调'] },
  { category: '工作', name: '进度', keywords: ['进度', '状态', '推进', '阻塞', '延期', '完成度', '继续', '当前'] },
  { category: '工作', name: '复盘', keywords: ['复盘', '总结', '教训', '回顾', '得失', '改进', '结论'] },
  { category: '生活', name: '日记', keywords: ['日记', '心情', '经历', '日常', '生活记录'] },
  { category: '生活', name: '健康', keywords: ['健康', '睡眠', '运动', '饮食', '体检', '锻炼'] },
  { category: '生活', name: '财务', keywords: ['财务', '花销', '预算', '收入', '报销', '账单'] },
  { category: '生活', name: '购物', keywords: ['购物', '下单', '购买', '商品', '价格', '清单'] },
  { category: '生活', name: '旅行', keywords: ['旅行', '出行', '酒店', '机票', '路线', '攻略'] },
  { category: '创意', name: '想法', keywords: ['想法', '构思', '脑洞', 'idea', '点子', '念头'] },
  { category: '创意', name: '灵感', keywords: ['灵感', '启发', '触发', '顿悟', '火花'] },
  { category: '创意', name: '计划', keywords: ['计划', '规划', '安排', '路线图', '步骤', '阶段'] },
  { category: '创意', name: '设计', keywords: ['设计', '交互', '视觉', '布局', '样式', '原型'] },
  { category: '内容', name: '写作', keywords: ['写作', '文章', '草稿', '文案', '表达', '撰写'] },
  { category: '内容', name: '素材', keywords: ['素材', '资料', '案例', '来源', '收集', '备选'] },
  { category: '内容', name: '引用', keywords: ['引用', '引述', '原话', '链接', '出处', 'reference'] },
  { category: '内容', name: '摘录', keywords: ['摘录', '摘抄', '片段', '选段', '原句'] },
  { category: '元标签', name: 'TODO', keywords: ['todo', '待办', '待处理', '稍后', '记得'] },
  { category: '元标签', name: '重要', keywords: ['重要', '关键', '优先', '必须', '紧急'] },
  { category: '元标签', name: '临时', keywords: ['临时', '随手', '暂存', '草记', '临记'] },
  { category: '元标签', name: '归档', keywords: ['归档', '收尾', '已完成', '封存', '存档'] },
]

export const DEFAULT_TAG_NAMES = new Set(DEFAULT_TAG_DEFINITIONS.map((definition) => definition.name))

export const DEFAULT_TAG_KEYWORDS = new Map(
  DEFAULT_TAG_DEFINITIONS.map((definition) => [definition.name, definition.keywords]),
)

export const TAG_STOPWORDS = new Set([
  '的',
  '了',
  '和',
  '是',
  '在',
  '与',
  '及',
  '把',
  '被',
  '也',
  '就',
  '还',
  '要',
  '有',
  '我',
  '你',
  '他',
  '她',
  '它',
  '们',
  '一个',
  '这个',
  '那个',
  '这些',
  '那些',
  '自己',
  '可以',
  '需要',
  '进行',
  '已经',
  '然后',
  '如果',
  '因为',
  '所以',
  '并且',
  '或者',
  '以及',
  '目前',
  '一下',
  '现在',
  '其中',
  '关于',
  '通过',
  '为了',
  'and',
  'the',
  'for',
  'with',
  'from',
  'into',
  'that',
  'this',
  'are',
  'was',
  'were',
  'have',
  'has',
  'had',
  'will',
  'shall',
  'would',
  'should',
  'could',
  'can',
  'may',
  'might',
  'not',
  'then',
  'than',
])

export const TECH_SIGNAL_PATTERNS = [
  /react/i,
  /vite/i,
  /typescript/i,
  /javascript/i,
  /sqlite/i,
  /schema/i,
  /api/i,
  /embedding/i,
  /vector/i,
  /向量/,
  /模型/,
  /siliconflow/i,
  /minimax/i,
  /bge/i,
  /代码/,
  /测试/,
  /接入/,
  /联调/,
  /部署/,
]

export const STRONG_TAG_HINTS: Record<string, RegExp[]> = {
  AI: [/embedding/i, /llm/i, /gpt/i, /向量/, /模型/, /siliconflow/i, /minimax/i, /bge/i],
  项目: [/mvp/i, /里程碑/, /需求/, /接入/, /验证/, /测试/, /联调/, /版本/],
  数据库: [/sqlite/i, /schema/i, /索引/, /数据库/, /查询/, /向量库/],
  编程: [/代码/, /开发/, /函数/, /脚本/, /实现/, /修复/],
}
